# Generated by Django 5.2 on 2025-06-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_bibliothequeutilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='genre',
            field=models.CharField(blank=True, choices=[('Roman', 'Roman'), ('Science-Fiction', 'Science-Fiction'), ('Fantasy', 'Fantasy'), ('Policier', 'Policier'), ('Biographie', 'Biographie'), ('Histoire', 'Histoire'), ('Science', 'Science')], max_length=100, null=True),
        ),
    ]
